<a href="https://colab.research.google.com/github/Daniel-F78/SSN/blob/main/Problema_de_Implementaci%C3%B3n_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problemas a resolver**

Problema 1: Demonstración de cálculo usando lenguaje de programación.

Debo hallar los momentos y ejes principales de inercia de  un sólido rígido sabiendo su tensor en un estado previo a la diagonalización, ejercicio proveniente de la asignatura de Ampliación de la Física Clásica.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
I=np.array([[5,-1,0],[-1,5,0],[0,0,3]])
print("Tensor")
print(I)

Tensor
[[ 5 -1  0]
 [-1  5  0]
 [ 0  0  3]]


Matemáticamente hablando, los momentos de inercia de nuestro sólido rígido serán los eigenvalues (vaps) del Tensor (que vamos a tratar como una matriz aunque no sea del todo cierto) y los ejes principales de inercia serán los eigenvectors (veps).

In [ ]:
Vaps,Veps=np.linalg.eig(I)
print("Vaps")
print(Vaps)
print("Veps")
print(Veps)

Vaps
[6. 4. 3.]
Veps
[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


Así se muestra que los momentos de Inercia que tiene nuestro sólido rígido son:

In [ ]:
I1=Vaps[0]
I2=Vaps[1]
I3=Vaps[2]
print("I1:",I1)
print("I2:",I2)
print("I3:",I3)

I1: 6.0
I2: 4.0
I3: 3.0


Y que los ejes principales de inercia son:

In [ ]:
v1=Veps[:,0]
v2=Veps[:,1]
v3=Veps[:,2]
print("v1:",v1)
print("v2:",v2)
print("v3:",v3)

v1: [ 0.70710678 -0.70710678  0.        ]
v2: [0.70710678 0.70710678 0.        ]
v3: [0. 0. 1.]
